/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API 프로세스 생존 여부 확인
         * @description 모델 상태와 무관한 API 프로세스의 기본 생존 정보를 반환합니다.
         */
        get: operations["liveness_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API와 모델의 요청 처리 준비 여부 확인
         * @description 현재 적재된 모델의 준비 상태와 식별 정보를 반환합니다.
         */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 고객 이탈 가능성 예측
         * @description 검증된 고객 정보로 이탈 여부와 이탈 확률을 예측합니다.
         */
        post: operations["create_prediction_api_v1_predictions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 팀 계정 회원가입
         * @description 새 팀 계정을 만들고 사용자 정보를 반환합니다.
         */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 팀 계정 로그인
         * @description 자격 증명을 검증하고 HttpOnly 세션 쿠키를 발급합니다.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 로그인 사용자 조회
         * @description 현재 인증 쿠키에 연결된 사용자 정보를 반환합니다.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 브라우저의 인증 쿠키를 삭제합니다.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthResponse
         * @description 회원가입·로그인 성공 응답입니다.
         */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description API와 적재된 모델의 준비 상태 응답입니다.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Model Loaded */
            model_loaded: boolean;
            /** Model Name */
            model_name: string;
            /** Model Artifact */
            model_artifact: string;
            /** Manifest Generated At */
            manifest_generated_at: string;
        };
        /**
         * LivenessResponse
         * @description API 프로세스의 생존 상태 응답입니다.
         */
        LivenessResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /**
         * LoginRequest
         * @description 팀 계정 로그인 요청입니다.
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Remember Me
             * @default false
             */
            remember_me: boolean;
        };
        /**
         * PredictionRequest
         * @description 학습된 분류 파이프라인이 요구하는 고객 특성 입력값입니다.
         */
        PredictionRequest: {
            /** Customer Age */
            customer_age: number;
            /**
             * Gender
             * @enum {string}
             */
            gender: "F" | "M";
            /** Dependent Count */
            dependent_count: number;
            /**
             * Education Level
             * @enum {string}
             */
            education_level: "College" | "Doctorate" | "Graduate" | "High School" | "Post-Graduate" | "Uneducated" | "Unknown";
            /**
             * Marital Status
             * @enum {string}
             */
            marital_status: "Divorced" | "Married" | "Single" | "Unknown";
            /**
             * Income Category
             * @enum {string}
             */
            income_category: "$120K +" | "$40K - $60K" | "$60K - $80K" | "$80K - $120K" | "Less than $40K" | "Unknown";
            /**
             * Card Category
             * @enum {string}
             */
            card_category: "Blue" | "Gold" | "Platinum" | "Silver";
            /** Months On Book */
            months_on_book: number;
            /** Total Relationship Count */
            total_relationship_count: number;
            /** Months Inactive 12 Mon */
            months_inactive_12_mon: number;
            /** Contacts Count 12 Mon */
            contacts_count_12_mon: number;
            /** Credit Limit */
            credit_limit: number;
            /** Total Revolving Bal */
            total_revolving_bal: number;
            /** Avg Open To Buy */
            avg_open_to_buy: number;
            /** Total Amt Chng Q4 Q1 */
            total_amt_chng_q4_q1: number;
            /** Total Trans Amt */
            total_trans_amt: number;
            /** Total Trans Ct */
            total_trans_ct: number;
            /** Total Ct Chng Q4 Q1 */
            total_ct_chng_q4_q1: number;
            /** Avg Utilization Ratio */
            avg_utilization_ratio: number;
        };
        /**
         * PredictionResponse
         * @description 고객 이탈 예측 결과와 사용된 모델 정보를 반환하는 응답입니다.
         */
        PredictionResponse: {
            /** Prediction */
            prediction: number;
            /** Status */
            status: string;
            /** Churn Probability */
            churn_probability: number;
            /** Decision Threshold */
            decision_threshold: number;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
        };
        /**
         * SignupRequest
         * @description 팀 계정 회원가입 요청입니다.
         */
        SignupRequest: {
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
        };
        /**
         * UserResponse
         * @description 외부에 공개할 수 있는 사용자 정보입니다.
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["UserRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserRole
         * @description CardOps 팀 사용자의 업무 역할입니다.
         * @enum {string}
         */
        UserRole: "admin" | "analyst" | "operations" | "marketing";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_prediction_api_v1_predictions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
