/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API 프로세스 생존 여부 확인
         * @description 모델 상태와 무관한 API 프로세스의 기본 생존 정보를 반환합니다.
         */
        get: operations["liveness_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API와 모델의 요청 처리 준비 여부 확인
         * @description 현재 적재된 모델의 준비 상태와 식별 정보를 반환합니다.
         */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 고객 이탈 가능성 예측
         * @description 검증된 고객 정보로 이탈 여부와 이탈 확률을 예측합니다.
         */
        post: operations["create_prediction_api_v1_predictions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팀 계정 목록 조회
         * @description 담당자 선택과 관리자 화면에서 사용할 팀 계정을 조회합니다.
         */
        get: operations["list_team_members_api_v1_auth_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 팀 계정 역할·활성 상태 변경
         * @description 관리자가 팀 계정의 역할과 활성 상태를 변경합니다.
         */
        patch: operations["update_team_member_api_v1_auth_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 팀 계정 회원가입
         * @description 새 팀 계정을 만들고 사용자 정보를 반환합니다.
         */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 팀 계정 로그인
         * @description 자격 증명을 검증하고 HttpOnly 세션 쿠키를 발급합니다.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 로그인 사용자 조회
         * @description 현재 인증 쿠키에 연결된 사용자 정보를 반환합니다.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 브라우저의 인증 쿠키를 삭제합니다.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최신 고객 분석 결과 목록 조회
         * @description 로그인 사용자가 고객별 최신 분석 결과를 필터·페이지 단위로 조회합니다.
         */
        get: operations["list_customer_insights_api_v1_customer_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-insights/history/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 고객 분석 이력 조회
         * @description 고객의 분석 시점별 이탈 확률과 활동성 변화를 반환합니다.
         */
        get: operations["get_customer_insight_history_api_v1_customer_insights_history__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-insights/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 고객별 최신 분석 결과 상세 조회
         * @description 로그인 사용자가 고객 특성과 최신 분석 결과를 함께 조회합니다.
         */
        get: operations["get_customer_insight_api_v1_customer_insights__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model-runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최근 성공 모델 배치 조회
         * @description 대시보드에서 데이터 갱신 시각과 사용 모델을 확인할 수 있게 합니다.
         */
        get: operations["get_latest_batch_api_v1_model_runs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaign-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 캠페인 대상 목록 조회
         * @description 인증된 사용자가 캠페인 처리 큐를 조회합니다.
         */
        get: operations["list_campaign_targets_api_v1_campaign_targets_get"];
        put?: never;
        /**
         * 캠페인 대상 등록
         * @description 분석 결과를 캠페인 처리 대상으로 등록합니다.
         */
        post: operations["create_campaign_target_api_api_v1_campaign_targets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaign-targets/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 캠페인 대상 처리 상태 변경
         * @description 캠페인 대상의 담당자·상태·처리 결과를 저장합니다.
         */
        patch: operations["update_campaign_target_api_api_v1_campaign_targets__target_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthResponse
         * @description 회원가입·로그인 성공 응답입니다.
         */
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
        };
        /**
         * CampaignStatus
         * @description 캠페인 대상 고객의 업무 처리 상태입니다.
         * @enum {string}
         */
        CampaignStatus: "pending" | "assigned" | "contacted" | "completed" | "cancelled";
        /**
         * CampaignTargetCreateRequest
         * @description 분석 결과를 캠페인 업무 대상으로 등록하는 요청입니다.
         */
        CampaignTargetCreateRequest: {
            /** Customer Insight Id */
            customer_insight_id: number;
            /** Campaign Name */
            campaign_name: string;
            /** Assigned To User Id */
            assigned_to_user_id?: number | null;
        };
        /**
         * CampaignTargetListResponse
         * @description 캠페인 대상 목록과 페이지네이션 응답입니다.
         */
        CampaignTargetListResponse: {
            /** Items */
            items: components["schemas"]["CampaignTargetResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * CampaignTargetResponse
         * @description 캠페인 대상과 현재 업무 처리 상태입니다.
         */
        CampaignTargetResponse: {
            /** Id */
            id: number;
            /** Customer Id */
            customer_id: number;
            /** Customer Insight Id */
            customer_insight_id: number;
            /** Campaign Name */
            campaign_name: string;
            /** Assigned To User Id */
            assigned_to_user_id: number | null;
            /** Assigned To Display Name */
            assigned_to_display_name?: string | null;
            status: components["schemas"]["CampaignStatus"];
            /** Processed At */
            processed_at: string | null;
            /** Result */
            result: string | null;
            /** Result Notes */
            result_notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CampaignTargetUpdateRequest
         * @description 캠페인 대상의 담당자·상태·처리 결과를 변경하는 요청입니다.
         */
        CampaignTargetUpdateRequest: {
            status?: components["schemas"]["CampaignStatus"] | null;
            /** Assigned To User Id */
            assigned_to_user_id?: number | null;
            /** Result */
            result?: string | null;
            /** Result Notes */
            result_notes?: string | null;
        };
        /**
         * CustomerInsightDetailResponse
         * @description 고객 특성을 포함한 분석 결과 상세 응답입니다.
         */
        CustomerInsightDetailResponse: {
            /** Id */
            id: number;
            /** Customer Id */
            customer_id: number;
            /** Customer Snapshot Id */
            customer_snapshot_id?: number | null;
            /** Classification Run Id */
            classification_run_id: number;
            /** Regression Run Id */
            regression_run_id: number;
            /** Clustering Run Id */
            clustering_run_id: number;
            /** Churn Probability */
            churn_probability: number;
            risk_level: components["schemas"]["RiskLevel"];
            /** Expected Transaction Count */
            expected_transaction_count: number;
            /** Activity Gap */
            activity_gap: number;
            /** Cluster Name */
            cluster_name: string;
            /** Cluster Confidence */
            cluster_confidence?: number | null;
            /** Recommended Action */
            recommended_action: string;
            /** Reason Codes */
            reason_codes: string[] | {
                [key: string]: unknown;
            } | null;
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
            customer: components["schemas"]["CustomerProfileResponse"];
        };
        /**
         * CustomerInsightHistoryResponse
         * @description 고객 한 명의 분석 스냅샷 이력입니다.
         */
        CustomerInsightHistoryResponse: {
            /** Customer Id */
            customer_id: number;
            /** Items */
            items: components["schemas"]["CustomerInsightResponse"][];
        };
        /**
         * CustomerInsightListResponse
         * @description 고객 분석 결과 목록과 페이지네이션·요약 통계입니다.
         */
        CustomerInsightListResponse: {
            /** Items */
            items: components["schemas"]["CustomerInsightResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
            stats: components["schemas"]["CustomerInsightStats"];
        };
        /**
         * CustomerInsightResponse
         * @description 고객별 최신 분석 결과 목록 항목입니다.
         */
        CustomerInsightResponse: {
            /** Id */
            id: number;
            /** Customer Id */
            customer_id: number;
            /** Classification Run Id */
            classification_run_id: number;
            /** Regression Run Id */
            regression_run_id: number;
            /** Clustering Run Id */
            clustering_run_id: number;
            /** Churn Probability */
            churn_probability: number;
            risk_level: components["schemas"]["RiskLevel"];
            /** Expected Transaction Count */
            expected_transaction_count: number;
            /** Activity Gap */
            activity_gap: number;
            /** Cluster Name */
            cluster_name: string;
            /** Cluster Confidence */
            cluster_confidence?: number | null;
            /** Recommended Action */
            recommended_action: string;
            /** Reason Codes */
            reason_codes: string[] | {
                [key: string]: unknown;
            } | null;
            /**
             * Scored At
             * Format: date-time
             */
            scored_at: string;
        };
        /**
         * CustomerInsightStats
         * @description 필터가 적용된 분석 결과의 대시보드 요약 통계입니다.
         */
        CustomerInsightStats: {
            /** Total */
            total: number;
            /** Average Churn Probability */
            average_churn_probability: number;
            /** Risk Counts */
            risk_counts: {
                [key: string]: number;
            };
            /** Cluster Counts */
            cluster_counts: {
                [key: string]: number;
            };
        };
        /**
         * CustomerProfileResponse
         * @description 분석 상세 화면에 제공할 고객 원본 특성입니다.
         */
        CustomerProfileResponse: {
            /** Customer Id */
            customer_id: number;
            /** Customer Age */
            customer_age: number;
            /** Gender */
            gender: string;
            /** Dependent Count */
            dependent_count: number;
            /** Education Level */
            education_level: string;
            /** Marital Status */
            marital_status: string;
            /** Income Category */
            income_category: string;
            /** Card Category */
            card_category: string;
            /** Months On Book */
            months_on_book: number;
            /** Total Relationship Count */
            total_relationship_count: number;
            /** Months Inactive 12 Mon */
            months_inactive_12_mon: number;
            /** Contacts Count 12 Mon */
            contacts_count_12_mon: number;
            /** Credit Limit */
            credit_limit: number;
            /** Total Revolving Bal */
            total_revolving_bal: number;
            /** Avg Open To Buy */
            avg_open_to_buy: number;
            /** Total Amt Chng Q4 Q1 */
            total_amt_chng_q4_q1: number;
            /** Total Trans Amt */
            total_trans_amt: number;
            /** Total Trans Ct */
            total_trans_ct: number;
            /** Total Ct Chng Q4 Q1 */
            total_ct_chng_q4_q1: number;
            /** Avg Utilization Ratio */
            avg_utilization_ratio: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description API와 적재된 모델의 준비 상태 응답입니다.
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
            /** Model Loaded */
            model_loaded: boolean;
            /** Model Name */
            model_name: string;
            /** Model Artifact */
            model_artifact: string;
            /** Manifest Generated At */
            manifest_generated_at: string;
        };
        /**
         * LatestBatchResponse
         * @description 가장 최근 성공한 전체 모델 배치의 요약입니다.
         */
        LatestBatchResponse: {
            status: components["schemas"]["ModelRunStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Processed Rows */
            processed_rows: number | null;
            /** Dataset Sha256 */
            dataset_sha256: string | null;
            /** Runs */
            runs: components["schemas"]["ModelRunResponse"][];
        };
        /**
         * LivenessResponse
         * @description API 프로세스의 생존 상태 응답입니다.
         */
        LivenessResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /**
         * LoginRequest
         * @description 팀 계정 로그인 요청입니다.
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Remember Me
             * @default false
             */
            remember_me: boolean;
        };
        /**
         * ModelRunResponse
         * @description 모델 배치 실행 이력의 외부 응답 구조입니다.
         */
        ModelRunResponse: {
            /** Id */
            id: number;
            /** Task */
            task: string;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Artifact Sha256 */
            artifact_sha256: string;
            /** Dataset Sha256 */
            dataset_sha256: string | null;
            /** Decision Policy Sha256 */
            decision_policy_sha256: string | null;
            /** Medium Threshold */
            medium_threshold: number | null;
            /** High Threshold */
            high_threshold: number | null;
            /** Activity Gap Quantile */
            activity_gap_quantile: number | null;
            status: components["schemas"]["ModelRunStatus"];
            /** Processed Rows */
            processed_rows: number | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
        };
        /**
         * ModelRunStatus
         * @description 모델 배치 실행의 처리 상태입니다.
         * @enum {string}
         */
        ModelRunStatus: "running" | "succeeded" | "failed";
        /**
         * PredictionRequest
         * @description 학습된 분류 파이프라인이 요구하는 고객 특성 입력값입니다.
         */
        PredictionRequest: {
            /** Customer Age */
            customer_age: number;
            /**
             * Gender
             * @enum {string}
             */
            gender: "F" | "M";
            /** Dependent Count */
            dependent_count: number;
            /**
             * Education Level
             * @enum {string}
             */
            education_level: "College" | "Doctorate" | "Graduate" | "High School" | "Post-Graduate" | "Uneducated" | "Unknown";
            /**
             * Marital Status
             * @enum {string}
             */
            marital_status: "Divorced" | "Married" | "Single" | "Unknown";
            /**
             * Income Category
             * @enum {string}
             */
            income_category: "$120K +" | "$40K - $60K" | "$60K - $80K" | "$80K - $120K" | "Less than $40K" | "Unknown";
            /**
             * Card Category
             * @enum {string}
             */
            card_category: "Blue" | "Gold" | "Platinum" | "Silver";
            /** Months On Book */
            months_on_book: number;
            /** Total Relationship Count */
            total_relationship_count: number;
            /** Months Inactive 12 Mon */
            months_inactive_12_mon: number;
            /** Contacts Count 12 Mon */
            contacts_count_12_mon: number;
            /** Credit Limit */
            credit_limit: number;
            /** Total Revolving Bal */
            total_revolving_bal: number;
            /** Avg Open To Buy */
            avg_open_to_buy: number;
            /** Total Amt Chng Q4 Q1 */
            total_amt_chng_q4_q1: number;
            /** Total Trans Amt */
            total_trans_amt: number;
            /** Total Trans Ct */
            total_trans_ct: number;
            /** Total Ct Chng Q4 Q1 */
            total_ct_chng_q4_q1: number;
            /** Avg Utilization Ratio */
            avg_utilization_ratio: number;
        };
        /**
         * PredictionResponse
         * @description 고객 이탈 예측 결과와 사용된 모델 정보를 반환하는 응답입니다.
         */
        PredictionResponse: {
            /** Prediction */
            prediction: number;
            /** Status */
            status: string;
            /** Churn Probability */
            churn_probability: number;
            /** Decision Threshold */
            decision_threshold: number;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
        };
        /**
         * RiskLevel
         * @description 고객 이탈 위험 등급입니다.
         * @enum {string}
         */
        RiskLevel: "low" | "medium" | "high";
        /**
         * SignupRequest
         * @description 팀 계정 회원가입 요청입니다.
         */
        SignupRequest: {
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
        };
        /**
         * TeamMemberResponse
         * @description 관리자와 캠페인 담당자 선택 화면에서 사용하는 팀 계정 정보입니다.
         */
        TeamMemberResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserAdminUpdateRequest
         * @description 관리자가 팀 계정의 역할과 활성 상태를 변경하는 요청입니다.
         */
        UserAdminUpdateRequest: {
            role?: components["schemas"]["UserRole"] | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * UserResponse
         * @description 외부에 공개할 수 있는 사용자 정보입니다.
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["UserRole"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserRole
         * @description CardOps 팀 사용자의 업무 역할입니다.
         * @enum {string}
         */
        UserRole: "admin" | "analyst" | "operations" | "marketing";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_prediction_api_v1_predictions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_team_members_api_v1_auth_users_get: {
        parameters: {
            query?: {
                /** @description 관리자만 비활성 계정까지 포함할 수 있습니다. */
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_team_member_api_v1_auth_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAdminUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_customer_insights_api_v1_customer_insights_get: {
        parameters: {
            query?: {
                /** @description 이탈 위험 등급 필터 */
                risk_level?: components["schemas"]["RiskLevel"] | null;
                /** @description 활동성 군집명 필터 */
                cluster_name?: string | null;
                /** @description 고객 ID 정확히 검색 */
                customer_id?: number | null;
                /** @description 정렬 기준 */
                sort_by?: "churn_probability" | "activity_gap" | "scored_at";
                /** @description 정렬 방향 */
                sort_order?: "asc" | "desc";
                /** @description 페이지 번호 */
                page?: number;
                /** @description 페이지당 결과 수 */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerInsightListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_insight_history_api_v1_customer_insights_history__customer_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerInsightHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_insight_api_v1_customer_insights__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerInsightDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_batch_api_v1_model_runs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestBatchResponse"];
                };
            };
        };
    };
    list_campaign_targets_api_v1_campaign_targets_get: {
        parameters: {
            query?: {
                /** @description 캠페인 처리 상태 필터 */
                status?: components["schemas"]["CampaignStatus"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignTargetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_campaign_target_api_api_v1_campaign_targets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignTargetCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignTargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_campaign_target_api_api_v1_campaign_targets__target_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignTargetUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignTargetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
